<?php ?>

<div class="rules__container green-bg-gradient">
	<!-- <h1 class="rules__title">JUICY JUICE<sup>&reg;</sup> “INCREDIBLE FAMILY ADVENTURE” OFFER &amp; SWEEPSTAKES OFFICIAL RULES</h1> -->
	<img style="padding: 20px 0px" src="assets/imgs/official-rules-title.png">
	<p class="no-b-margin">NO PURCHASE NECESSARY. A PURCHASE WILL NOT IMPROVE CHANCES OF WINNING.</p>

	<p>PROMOTION PERIOD: The Juicy Juice® "Incredible Family Adventure" Offer &amp; Sweepstakes ("Promotion") begins at 12:00 p.m. Eastern Time (“ET”) on May 1, 2018 and ends at 04:59 p.m. ET on October 31, 2018 (“Promotion Period”). The Promotion will consist of (i) a gift with purchase offer where eligible individuals can purchase specially marked Juicy Juice products and redeem corresponding product package codes to receive one (1) Fandango Promotional Code (the “Offer”); and (ii) a sweepstakes where individuals can enter a random drawing for a chance to win the grand prize outlined below (the “Sweepstakes”). The Administrator’s computer is the official time keeping device for this Promotion.</p>

	<p>ELIGIBILITY: The Promotion is open to legal residents of the fifty (50) United States and District of Columbia, 18 years of age or older (or the age of majority in their state of legal residence, whichever is older) as of May 1, 2018. Employees, officers, directors, and the members of their immediate families (spouse, parent, sibling and child and their respective spouses, regardless of where they reside) or households (whether or not related) of Harvest Hill Beverage Company (“Sponsor"), Black Diamond Media, Inc. (“Administrator”), Fandango Loyalty Solutions, LLC and Walt Disney Studios Motion Pictures (“Promotional Partner(s)”), and any of their respective affiliated companies, subsidiaries, advertising agencies and agencies/parties engaged in the development, production and distribution of Promotion materials (collectively, the “Promotion Entities”) are not eligible to participate in the Promotion. Void where prohibited. By participating in the Promotion, participants (“Participants”) agree to: (a) comply with these official rules (“Official Rules”) and all decisions of the Sponsor, which shall be final and binding in all matters relating to this Promotion; and (b) release and hold harmless each of the Promotion Entities and their respective agents, employees, officers, directors, successors and assigns, against any and all claims, injuries, or damages, arising out of or relating to participation in this Promotion and/or the use or misuse or redemption of a prize, and for any claims based on publicity rights, defamation, invasion of privacy, copyright infringement, trademark infringement or any other intellectual property related cause of action.</p>
	
	<p>HOW TO PARTICIPATE IN THE OFFER: During the Promotion Period, you can obtain an In-Pack code (“Code”) by purchasing one of the following specially marked participating products: 64 oz. Juicy Juice® (any one (1) of the six (6) participating varieties) or 8 Pack of 6.75 oz. Juicy Juice® juice boxes (any one (1) of the four (4) participating varieties) (each, a “Participating Product”); the Code is printed inside the bottle wrap for the 64 oz. product and printed on the inside paper wrap cover of the 8 Pack card. Then, visit www.juicyjuice.com/Incredibles2, click on the Promotion link and follow the instructions to provide your name, email address and enter in three (3) In-Pack Codes to receive one (1) Fandango Promotional Code via email which will be valid for a child admission (up to $7.50 total ticket and convenience fee value) to see Incredibles 2 or any Disney movie, while supplies last. Each In-Pack Code may only be used once. In-Pack Codes have no cash value. Each Participant may submit up to twelve (12) In-Pack Codes (to submit a maximum of four (4) Offer requests) per calendar month throughout the Promotion Period. </p>
	
	<p class="no-b-margin">HOW TO ENTER THE SWEEPSTAKES: There are two (2) ways to enter the Sweepstakes. 1) Offer Redemption: Participants will automatically receive one (1) entry in the Sweepstakes random drawing after following the instructions above to complete and submit an Offer request. Entry received will be subject to verification and approval of Offer request. Entry requests via Offer redemption must be received by 04:59 p.m. ET on October 31, 2018. Or 2) Mail-in: To receive one (1) Sweepstakes entry by mail without making a purchase or submitting an Offer request, send a hand-written 3” x 5” card with your name, physical address and email address to: Juicy Juice “Incredible Family Adventure” Sweepstakes, Dept. S7563, PO Box 4006, Grand Rapids, MN 55730-4006. To receive future marketing communications from Harvest Hill Beverage Company, via email only, please hand-write “OPT-IN” on the card submitted. Limit one (1) entry per outer stamped envelope per person per day. For the avoidance of doubt, there is a maximum limit of twenty-four (24) Sweepstakes entries per person throughout the Promotion Period, regardless of method of entry. All mail-in entry requests must be postmarked by October 31, 2018 and received by November 5, 2018.</p>
	
	<p>Only one (1) e-mail address may be used by a Participant to enter the Promotion. Multiple Participants are not permitted to share the same email address. Any attempt by any Participant to obtain more than the stated number of offers requests/sweepstakes entries by using multiple/different email addresses, identities, registrations, accounts, logins, or any other methods will void that Participant’s offer requests/sweepstakes entries and that Participant may be disqualified. Suspected use of any automated or robotic system to enter is prohibited and will automatically result in disqualification, in Sponsor’s sole discretion. For the purposes of this Promotion, a “day” is a calendar day, beginning at 12:00 a.m. ET and ending at 11:59 p.m. ET, except for the first day of the Promotion Period, which shall begin at 12:00 p.m. ET, and the last day of the Promotion Period, which shall end at 04:59 p.m. ET.</p>

	<p class="no-b-margin">SWEEPSTAKES WINNER SELECTION, NOTIFICATION, AND VERIFICATION: One (1) potential grand prize winner will be selected in a random drawing of all eligible entries received, to be held on or about November 15, 2018. Drawing will be conducted by Administrator, and all decisions are final. On or about November 16, 2018, the Potential winner will be contacted by telephone, email or mail at Administrator’s discretion. If potential winner cannot be reached within three (3) days of first notification attempt, if prize or prize notification is returned as undeliverable, if potential winner rejects his/her prize, or in the event of noncompliance with these Official Rules, such prize will be forfeited and an alternate winner will be selected from all remaining eligible entries. Upon forfeiture of prize, no compensation will be given. Odds of winning the grand prize are dependent on the number of eligible Sweepstakes entries received throughout the Promotion Period. Potential grand prize winner will be required to sign and return an Affidavit of Eligibility and Liability/Publicity Release (where lawful) within five (5) days of notification that they are a potential winner. If potential grand prize winner fails to comply with these Official Rules and/or to submit the required documentation within the designated time period, he/she will automatically be disqualified and the prize may be awarded to an alternate winner.</p>
	
	<p>SWEEPSTAKES GRAND PRIZE (1): An Incredible Family Adventure, awarded in the form of a $10,000 check made payable to the winner to create an incredible family adventure of their choice or anything they choose. Approximate Retail Value (“ARV”) of grand prize: $10,000. All federal, state, and local taxes, fees, are the sole responsibility of the grand prize winner.</p>
	
	<p>SWEEPSTAKES PRIZE CONDITIONS: All prize details are at Sponsor’s sole discretion. No transfer, substitution or cash equivalent for the grand prize, in whole or in part, will be permitted except at Sponsor's sole discretion, and only then for a prize of greater or equal value determined by Sponsor. Prize award is subject to verification of eligibility and compliance with the terms of these Official Rules. The prize restrictions/conditions stated herein are not all-inclusive and may be subject to additional restrictions/conditions. Noncompliance with any of these Official Rules may result in disqualification. The grand prize will be awarded provided a sufficient number of eligible entries are received.</p>
	
	<p>FANDANGO PROMOTIONAL CODE TERMS & CONDITIONS: Fandango Promotional Code is good towards one movie ticket (up to $7.50 total ticket and convenience fee value) to see Incredibles 2 or any other Disney movie at Fandango partner theaters in the U.S. Fandango Promotional Code must be redeemed March, 31 2019 and is void if not redeemed by the expiration date. Only valid for purchase of movie tickets made at www.fandango.com/promo/juicyjuice or via the Fandango app and cannot be redeemed directly at any Fandango partner theater box office. If lost or stolen, cannot be replaced and there will be no refunds. No cash value. Not valid with any other offer. Fandango Promotional Code is valid for one-time use only. Not for resale; void if sold or exchanged. If cost of movie ticket with Fandango’s convenience fee included is more than maximum value of the Fandango Promotional Code, then user must pay the difference. Fandango Loyalty Solutions, LLC is not a sponsor or co-sponsor of this program. The redemption of Fandango Promotional Code is subject to Fandango’s Terms and Policies at www.fandango.com/terms-and-policies. All Rights Reserved.</p>
	
	<p>GENERAL: The Sponsor is not responsible for (i) late, lost, delayed, not received, damaged, misdirected, incomplete, stolen, or garbled/illegible entries/requests or Codes; or (ii) failure to receive mail/entries/requests due to transmission failures or technical failures of any kind, including, without limitation, malfunctioning of any network, Internet Service Provider (ISP), servers, access providers, hardware or software, whether originating with sender or recipient; or (iii) any problems or technical malfunctions of any telephone network or lines, computer online systems or servers, computer software problems or traffic congestion on the internet or at any website and assume no liability for damage to Participant’s or any person's computer resulting from participating in the Promotion. In the event of a dispute as to the identity of a winner based on an e-mail address, the winning entry will be deemed to have been made by the authorized account holder of the e-mail address at the time of entry. “Authorized account holder” is the natural person who is assigned an e-mail address by an internet service provider or other organization responsible for assigning e-mail addresses for the domain associated with the e-mail address in question. PARTICIPANTS, BY PARTICIPATING, AGREE THAT PROMOTION ENTITIES, WALT DISNEY STUDIOS MOTION PICTURES, FANDANGO LOYALTY SOLUTIONS, LLC, BLACK DIAMOND MEDIA, INC., BHSC GLOBAL MARKETING, LLC, BRAND CONNECTIONS, LLC, AND THEIR PARENT, AFFILIATES, SUBSIDIARIES, PRIZE SUPPLIERS, ADVERTISING AND PROMOTION AGENCIES, AND WEBSITE PROVIDERS/WEB MASTERS, AND ALL OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, REPRESENTATIVES AND AGENTS WILL HAVE NO LIABILITY WHATSOEVER FOR, AND SHALL BE HELD HARMLESS BY PARTICIPANTS AGAINST, ANY LIABILITY, FOR ANY INJURIES, LOSSES OR DAMAGES OF ANY KIND, INCLUDING DEATH, TO PERSONS, OR PROPERTY RESULTING IN WHOLE OR IN PART, DIRECTLY OR INDIRECTLY, FROM ACCEPTANCE, POSSESSION, REDEMPTION, MISUSE OR USE OF A PRIZE OR PARTICIPATION IN THIS PROMOTION. UNDER NO CIRCUMSTANCES WILL ANY PARTICIPANT BE PERMITTED TO OBTAIN AWARDS FOR, AND PARTICIPANTS HEREBY WAIVE ALL RIGHTS TO CLAIM, PUNITIVE, INCIDENTAL, CONSEQUENTIAL, OR ANY OTHER DAMAGES WHATSOEVER. IN NO EVENT SHALL SPONSOR BE LIABLE TO ANY PARTICIPANT FOR DAMAGES THAT EXCEED THE VALUE OF THE PRIZE TO BE AWARDED TO THE INDIVIDUAL PARTICIPANT.</p>

	<p>THIS PROMOTION IS GOVERNED BY, AND WILL BE CONSTRUED IN ACCORDANCE WITH, THE LAWS OF THE STATE OF CONNECTICUT, AND THE FORUM AND VENUE FOR ANY DISPUTE SHALL BE IN CONNECTICUT. IF THE CONTROVERSY OR CLAIM IS NOT OTHERWISE RESOLVED THROUGH DIRECT DISCUSSIONS OR MEDIATION, IT SHALL THEN BE RESOLVED BY FINAL AND BINDING ARBITRATION ADMINISTERED BY JUDICIAL ARBITRATION AND MEDIATION SERVICES, INC., IN ACCORDANCE WITH ITS STREAMLINED ARBITRATION RULES AND PROCEDURES OR SUBSEQUENT VERSIONS THEREOF (“JAMS RULES”). THE JAMS RULES FOR SELECTION OF AN ARBITRATOR SHALL BE FOLLOWED, EXCEPT THAT THE ARBITRATOR SHALL BE EXPERIENCED AND LICENSED TO PRACTICE LAW IN CONNECTICUT. THE REMEDY FOR ANY CLAIM SHALL BE LIMITED TO ACTUAL DAMAGES, AND IN NO EVENT SHALL ANY PARTY BE ENTITLED TO RECOVER PUNITIVE, EXEMPLARY, CONSEQUENTIAL, OR INCIDENTAL DAMAGES, INCLUDING ATTORNEYS’ FEES OR OTHER SUCH RELATED COSTS OF BRINGING A CLAIM, OR TO RESCIND THIS AGREEMENT OR SEEK INJUNCTIVE OR ANY OTHER EQUITABLE RELIEF. PARTICIPANTS AGREE ANY DISPUTE WILL BE RESOLVED INDIVIDUALLY, WITHOUT RESORT TO CLASS ACTION. </p>
	
	<p>ANY AND ALL DISPUTES, CLAIMS AND CAUSES OF ACTION ARISING OUT OF OR CONNECTED WITH THE INTELLECTUAL PROPERTY OF WALT DISNEY STUDIOS MOTION PICTURES, SHALL BE RESOLVED INDIVIDUALLY, WITHOUT RESORT TO ANY FORM OF CLASS ACTION, SHALL BE GOVERNED AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF CALIFORNIA AND IN THE EVENT OF ANY DISPUTE, ALL PARTICIPANTS IRREVOCABLY CONSENT TO THE JURISDICTION OF THE STATE AND FEDERAL COURTS LOCATED IN LOS ANGELES, CALIFORNIA TO RESOLVE SUCH DISPUTES.</p>
	
	<p class="no-b-margin">This Promotion is subject to all applicable federal, state and local laws and regulations. All entries and offer requests become the property of the Sponsor and will not be returned. By completing the online registration form, all Participants and winner consents to the use of their names and/or photographs for publicity purposes without compensation, worldwide in perpetuity and in any form of media including the internet, and consent to the collection, use and distribution of their personal information by the Sponsor for the purposes of running the Promotion. Sponsor will not sell or transmit this information to third parties except for the purposes of administering the Promotion, unless you agree otherwise. For information on use of personal information in connection with this Promotion, see Sponsor’s privacy policy posted at http://juicyjuice.com/privacy/.</p>

	<p>If for any reason, the Promotion is not capable of being completed as planned including, but not limited to computer virus, bugs, tampering, fraud, technical failures, printing, administrative, or other causes beyond the control of the Sponsor, the Sponsor reserves the right, in its sole discretion to cancel or suspend this Promotion or to modify these Promotion rules, at any time. Any attempt to deliberately damage any website or electronic communication or to undermine the legitimate operation of this Promotion is a violation of criminal and civil laws, and should such an attempt be made, Sponsor reserves the right to seek remedies and damages to the fullest extent permitted by law. </p>

	<p>In the event of any discrepancy or inconsistency between the terms and conditions of these Official Rules and disclosures or other statements contained in any Promotion-related materials, including but not limited to the official entry page, or point of sale, television, print or online advertising, the terms and conditions of these Official Rules shall prevail, govern and control.</p>
	
	<p>WINNER’S NAME: To obtain the name of the Sweepstakes grand prize winner, available after November 30, 2018, send a self-addressed stamped envelope to Juicy Juice “Incredible Family Adventure” Sweepstakes Winner’s Name Request, 9 Union Square #229, Southbury, CT 06488. All requests must be received by December 31, 2018.</p>
	
	<p class="no-b-margin">SPONSOR: Harvest Hill Beverage Company, 1 High Ridge Park, Stamford, CT 06905.</p>

	<p>ADMINISTRATOR:  Black Diamond Media, Inc., 574 Heritage Road, Suite 201A, Southbury, CT 06488.</p>

	<p>THIS PROMOTION IS GOVERNED BY, AND WILL BE CONSTRUED IN ACCORDANCE WITH, THE LAWS OF THE STATE OF CONNECTICUT, AND THE FORUM AND VENUE FOR ANY DISPUTE SHALL BE IN CONNECTICUT. IF THE CONTROVERSY OR CLAIM IS NOT OTHERWISE RESOLVED THROUGH DIRECT DISCUSSIONS OR MEDIATION, IT SHALL THEN BE RESOLVED BY FINAL AND BINDING ARBITRATION ADMINISTERED BY JUDICIAL ARBITRATION AND MEDIATION SERVICES, INC., IN ACCORDANCE WITH ITS STREAMLINED ARBITRATION RULES AND PROCEDURES OR SUBSEQUENT VERSIONS THEREOF (“JAMS RULES”). THE JAMS RULES FOR SELECTION OF AN ARBITRATOR SHALL BE FOLLOWED, EXCEPT THAT THE ARBITRATOR SHALL BE EXPERIENCED AND LICENSED TO PRACTICE LAW IN CONNECTICUT. THE REMEDY FOR ANY CLAIM SHALL BE LIMITED TO ACTUAL DAMAGES, AND IN NO EVENT SHALL ANY PARTY BE ENTITLED TO RECOVER PUNITIVE, EXEMPLARY, CONSEQUENTIAL, OR INCIDENTAL DAMAGES, INCLUDING ATTORNEYS’ FEES OR OTHER SUCH RELATED COSTS OF BRINGING A CLAIM, OR TO RESCIND THIS AGREEMENT OR SEEK INJUNCTIVE OR ANY OTHER EQUITABLE RELIEF. PARTICIPANTS AGREE ANY DISPUTE WILL BE RESOLVED INDIVIDUALLY, WITHOUT RESORT TO CLASS ACTION.</p>

	<p>ANY AND ALL DISPUTES, CLAIMS AND CAUSES OF ACTION ARISING OUT OF OR CONNECTED WITH THE INTELLECTUAL PROPERTY OF WALT DISNEY STUDIOS MOTION PICTURES, SHALL BE RESOLVED INDIVIDUALLY, WITHOUT RESORT TO ANY FORM OF CLASS ACTION, SHALL BE GOVERNED AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF CALIFORNIA AND IN THE EVENT OF ANY DISPUTE, ALL PARTICIPANTS IRREVOCABLY CONSENT TO THE JURISDICTION OF THE STATE AND FEDERAL COURTS LOCATED IN LOS ANGELES, CALIFORNIA TO RESOLVE SUCH DISPUTES.</p>

	<p>This Promotion is subject to all applicable federal, state and local laws and regulations. All entries and offer requests become the property of the Sponsor and will not be returned. By completing the online registration form, all Participants and winner consents to the use of their names and/or photographs for publicity purposes without compensation, worldwide in perpetuity and in any form of media including the internet, and consent to the collection, use and distribution of their personal information by the Sponsor for the purposes of running the Promotion. Sponsor will not sell or transmit this information to third parties except for the purposes of administering the Promotion, unless you agree otherwise. For information on use of personal information in connection with this Promotion, see Sponsor’s privacy policy posted at http://juicyjuice.com/privacy/.</p>
	
	<p>If for any reason, the Promotion is not capable of being completed as planned including, but not limited to computer virus, bugs, tampering, fraud, technical failures, printing, administrative, or other causes beyond the control of the Sponsor, the Sponsor reserves the right, in its sole discretion to cancel or suspend this Promotion or to modify these Promotion rules, at any time. Any attempt to deliberately damage any website or electronic communication or to undermine the legitimate operation of this Promotion is a violation of criminal and civil laws, and should such an attempt be made, Sponsor reserves the right to seek remedies and damages to the fullest extent permitted by law.</p>

	<p>In the event of any discrepancy or inconsistency between the terms and conditions of these Official Rules and disclosures or other statements contained in any Promotion-related materials, including but not limited to the official entry page, or point of sale, television, print or online advertising, the terms and conditions of these Official Rules shall prevail, govern and control.</p>
	
	<p>WINNER’S NAME: To obtain the name of the Sweepstakes grand prize winner, available after November 30, 2018, send a self-addressed stamped envelope to Juicy Juice “Incredible Family Adventure” Sweepstakes Winner’s Name Request, 9 Union Square #229, Southbury, CT 06488. All requests must be received by December 31, 2018.</p>
	
	<p class="no-b-margin">SPONSOR: Harvest Hill Beverage Company, 1 High Ridge Park, Stamford, CT 06905.</p>

	<p class="no-b-margin">ADMINISTRATOR:  Black Diamond Media, Inc., 574 Heritage Road, Suite 201A, Southbury, CT 06488.</p>
</div>